apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 36000
        - containerPort: 36001
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  ports:
  - name: ftps-21
    port: 21
    targetPort: 21
    protocol: TCP
  - name: ftps-36000
    port: 36000
    targetPort: 36000
    protocol: TCP
  - name: ftps-36001
    port: 36001
    targetPort: 36001
    protocol: TCP
  selector:
    app: ftps