apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: my_telegraf
        imagePullPolicy: Never
        name: telegraf
        ports:
        - containerPort: 3306
          name: telegraf
        volumeMounts:
        - name: telegraf-data
          mountPath: /var/lib/telegraf
      volumes:
      - name: telegraf-data
        persistentVolumeClaim:
          claimName: telegraf-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: telegraf
  selector:
    app: telegraf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegraf-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
